# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend0bit', '0007_auto_20171016_1559')
    ]

    state_operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('contents', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_edited_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'posts_post',
            },
            bases=(models.Model,),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
