# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
