# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend0bit', '0002_auto_20160918_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=64)),
                ('contents', models.TextField()),
            ],
        ),
    ]
