# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend0bit', '0003_staticpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='url',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
