# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 21:05
from __future__ import unicode_literals

import backend0bit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend0bit', '0005_staticpage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_edited_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='order',
            field=models.IntegerField(default=backend0bit.models.get_next_order, unique=True),
        ),
    ]
