# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend0bit', '0006_auto_20170925_2105'),
    ]

    database_operations = [
        migrations.AlterModelTable('Post', 'posts_post')
    ]

    state_operations = [
        migrations.DeleteModel('Post')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
